### PR TITLE
Yxc

### PR DESCRIPTION
**Pull request by YixingChen**
Add the legacy IDF results for all the building types.

### CODE REVIEW

**Comment by mbadams5** [comment]
@YixingChen It is great that we have all the legacy IDFs simulated now. 

However, when you merged this into master (or merging master into your branch) you overwrote the hvac standards xlsx file which had my medium office changes in it. I can add them back in on my (local) large office branch.

Also there are still a couple merge conflict tags in the code base, [for example...](https://github.com/NREL/OpenStudio-Prototype-Buildings/blob/88ba5784ee0cf8468a0b128d10754432df8b9ff9/create_DOE_prototype_building/tests/create_DOE_prototype_building_Test.rb#L444)

**Comment by YixingChen** [comment]
Kaiyu and I will go through the files and clean the conflicts.

Yixing (Ethan) Chen
Simulation Research Group, EETD, LBNL

**Comment by YixingChen** [comment]
Hi All,

I just clean up the conflicts and successfully test the large hotels.

I also merge my changes in the hvac standard excel to the master branch.
Let me know if there are problems.

Yixing (Ethan) Chen
Simulation Research Group, EETD, LBNL

**Comment by KaiyuSun** [comment]
Thanks Yixing. It is able to run again.

 

Kaiyu

**Pull request merged**
